#
# Docker compose template using gluetun as a VPN in the same container stack.
# In this example, `gallery-dl.conf` is located in the same directory as the compose file.
# The environment variables for your VPN configuration can go in this file or a separate `.env` file in the same directory, or specify
# the location with `docker compose --env-file <location> up -d`.
#

services:
  gallery-dl-server:
    image: qx6ghqkz/gallery-dl-server:latest
    container_name: gdl-serv
    depends_on:
      - gluetun
    network_mode: service:gluetun
    user: 1000:1000
    volumes:
      - type: bind
        source: ./gallery-dl.conf
        target: /etc/gallery-dl.conf
      - type: bind
        source: ~/Downloads/gallery-dl
        target: /gallery-dl
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # gallery-dl-server ports
      - 9080:9080
    volumes:
      - ~/Documents/gluetun:/gluetun
    environment:
      # Configuration for Wireguard. See https://github.com/qdm12/gluetun?tab=readme-ov-file#setup for more details.
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
    restart: unless-stopped
